export const DEV_TICKER = [
  "Ship happens",
  "Console.log is therapy",
  "Merge first, regret later",
  "404: taste not found",
  "Move it 1px. Again",
  "The edge case has entered the chat",
  "The demo gods are always watching",
  "Pixels have feelings",
  "Hardcoded today, refactored never",
  "localhost:3000 is not a submission",
  "If it lags, it laughs at you",
  "Taste can't be npm installed",
  "Good design is invisible, bad design is a meme",
  "Your CSS is showing",
  "when the code finally compiles",
  "Funny is the hard part",
  "Six formats. Zero watermarks.",
  "Memes are the internet's native language",
];
